spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 10.36.147.26:2181
  protocol:
    port: 28810